export const BotTuning = {
    heal: {
        lowHp: 60,
        veryLowHp: 35,
    },
    boost: {
        threshold: 50,
        veryLowBoost: 25,
    },
    danger: {
        healMax: 0.35,
        retreatHealMax: 0.45,
        healCancelMin: 0.55,
        visibleUnarmedThreatScale: 0.45,
        boostQuickMax: 0.5,
        boostLongMax: 0.3,
        visibleTargetAdd: 0.38,
        distanceRef: 20,
        distanceAdd: 0.22,
        lowHpAdd: 0.22,
        activeReloadAdd: 0.18,
        emptyReloadAdd: 0.14,
        recentDamageAdd: 0.12,
        gasEmergencyAdd: 0.25,
    },
    unarmed: {
        shownGunDangerAdd: 0.28,
        visibleUnarmedDangerDiscount: 0.14,
        distractedArmedDangerRelief: 0.16,
        distractedFightRadius: 10,
        hostileProximityRef: 8,
        shownGunObjectPenalty: 300,
        distractedShownGunObjectRelief: 180,
        unarmedHostileObjectBonus: 130,
        objectBaseBonus: 190,
        shownGunLootBonus: 180,
        shownGunNonGunLootPenalty: 170,
        distractedShownGunLootRelief: 100,
    },
    combat: {
        recentlyDamagedWindowSec: 0.45,
        damageDodgeDurationSec: 0.35,
        stateHysteresisDist: 1.25,
        retreatStateCommitSec: 0.55,
        chaseStateCommitSec: 0.45,
        lootStateCommitSec: 0.6,
        strafeFlipSecMin: 0.25,
        strafeFlipSecMax: 0.6,
        strafeEnableMaxDist: 18,
        strafePerpDist: 8,
        enemyVeryCloseDist: 6,
        enemyCloseDist: 10,
    },
    navigation: {
        sameGoalDist: 2.5,
        arriveDist: 1.5,
        progressDist: 0.75,
        containerClosedHalfLen: 8,
        containerOpenHalfLen: 11,
        containerExitOutsideDist: 1.35,
        warehouseEntryInsideInset: 2.25,
        warehouseEntryExitOutsideDist: 1.6,
        detourTtlSec: 1.0,
        failedWaypointTtlSec: 2.5,
        failedWaypointDist: 2.0,
        forceDetourTtlSec: 1.25,
        stuckRepathAfterSec: 1.0,
        fallbackWaypointAfterSec: 3.0,
        fallbackCenterAfterSec: 4.0,
        detourSideShortDist: 4,
        detourSideLongDist: 8,
        detourForwardBiasDist: 3,
        wallSlideMinLength: 12,
        wallSlideMaxThickness: 3.5,
        wallSlideClearanceDist: 1.25,
        wallSlideSideDist: 6,
        wallEscapeDist: 3.5,
    },
    loot: {
        idleSearchDist: 14,
        opportunisticSearchDist: 7.5,
        opportunisticDangerMax: 0.32,
        unarmedGunBonus: 520,
        weaponUpgradeMinScore: 7,
    },
    objectInteract: {
        idleSearchDist: 12,
        opportunisticSearchDist: 7,
        opportunisticDangerMax: 0.28,
        breakAbortDangerMin: 0.4,
        maxDetourDist: 8,
        useReachSlack: 0.5,
        meleeApproachInset: 0.75,
        meleeArriveDist: 0.2,
        meleeMoveDeadzone: 0.2,
        stateCommitSec: 0.55,
        loadoutValuePenalty: 8,
        lootBaselineScore: 420,
        airdropBonus: 180,
        destroyTypeBonus: 45,
        lootEntryBonus: 30,
        manualDoorBaseScore: 920,
        buttonBaseScore: 860,
    },
    itemCancel: {
        bandageFinishWindowSec: 0.6,
        bandageMovingCommitProgress: 0.35,
        healthkitFinishWindowSec: 0.9,
        healthkitCommitProgress: 0.5,
    },
    optimization: {
        selectionCacheTtlSec: 0.2,
        selectionCacheMoveDist: 1.25,
        selectionCacheGoalDist: 1.75,
        failedLootCooldownSec: 1.4,
        failedObjectCooldownSec: 1.8,
        failedBlockerCooldownSec: 1.2,
    },
} as const;
