export const BotTuning = {
    heal: {
        lowHp: 60,
        veryLowHp: 35,
    },
    boost: {
        threshold: 50,
        veryLowBoost: 25,
    },
    danger: {
        healMax: 0.35,
        retreatHealMax: 0.45,
        healCancelMin: 0.55,
        boostQuickMax: 0.5,
        boostLongMax: 0.3,
    },
    combat: {
        recentlyDamagedWindowSec: 0.45,
        damageDodgeDurationSec: 0.35,
        strafeFlipSecMin: 0.25,
        strafeFlipSecMax: 0.6,
        strafeEnableMaxDist: 18,
        strafePerpDist: 8,
        enemyVeryCloseDist: 6,
        enemyCloseDist: 10,
    },
    navigation: {
        sameGoalDist: 2.5,
        arriveDist: 1.5,
        progressDist: 0.75,
        detourTtlSec: 1.0,
        failedWaypointTtlSec: 2.5,
        failedWaypointDist: 2.0,
        forceDetourTtlSec: 1.25,
        stuckRepathAfterSec: 1.0,
        fallbackWaypointAfterSec: 3.0,
        fallbackCenterAfterSec: 4.0,
        detourSideShortDist: 4,
        detourSideLongDist: 8,
        detourForwardBiasDist: 3,
    },
    loot: {
        idleSearchDist: 14,
        opportunisticSearchDist: 7.5,
        opportunisticDangerMax: 0.32,
        weaponUpgradeMinScore: 7,
    },
    itemCancel: {
        bandageFinishWindowSec: 0.6,
        healthkitFinishWindowSec: 0.9,
    },
} as const;
